#############################################################################
# Makefile for building: seqtube
# Generated by qmake (2.01a) (Qt 4.8.6) on: Sat Dec 13 03:27:38 2014
# Project:  seqtube.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug -o Makefile seqtube.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_SQL_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -O0 -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtSql -I/usr/include/qt4 -I. -I/usr/include/qca2/QtCrypto -I/usr/include/QtCrypto -I.
LINK          = g++
LFLAGS        = -Wl,-O1,--sort-common,--as-needed,-z,relro
LIBS          = $(SUBLIBS)  -L/usr/lib -L/usr/lib -lqca -lQtSql -lQtGui -lQtNetwork -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cc \
		ChatDialog.cc \
		NetSocket.cc \
		TextEdit.cc \
		MongMsg.cc \
		BlockRequest.cc \
		SharedFile2.cc \
		Block.cc \
		SearchDialog.cc \
		FileDownload.cc \
		sha1sum.cc \
		FileListItem.cc \
		Database.cc moc_main.cpp \
		moc_Database.cpp
OBJECTS       = main.o \
		ChatDialog.o \
		NetSocket.o \
		TextEdit.o \
		MongMsg.o \
		BlockRequest.o \
		SharedFile2.o \
		Block.o \
		SearchDialog.o \
		FileDownload.o \
		sha1sum.o \
		FileListItem.o \
		Database.o \
		moc_main.o \
		moc_Database.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/crypto.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		seqtube.pro
QMAKE_TARGET  = seqtube
DESTDIR       = 
TARGET        = seqtube

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)
	{ test -n "$(DESTDIR)" && DESTDIR="$(DESTDIR)" || DESTDIR=.; } && test $$(gdb --version | sed -e 's,[^0-9][^0-9]*\([0-9]\)\.\([0-9]\).*,\1\2,;q') -gt 72 && gdb --nx --batch --quiet -ex 'set confirm off' -ex "save gdb-index $$DESTDIR" -ex quit '$(TARGET)' && test -f $(TARGET).gdb-index && objcopy --add-section '.gdb_index=$(TARGET).gdb-index' --set-section-flags '.gdb_index=readonly' '$(TARGET)' '$(TARGET)' && rm -f $(TARGET).gdb-index || true

Makefile: seqtube.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/crypto.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libqca.prl \
		/usr/lib/libQtSql.prl \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtNetwork.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug -o Makefile seqtube.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_phonon.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/crypto.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libqca.prl:
/usr/lib/libQtSql.prl:
/usr/lib/libQtGui.prl:
/usr/lib/libQtNetwork.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug -o Makefile seqtube.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/seqtube1.0.0 || $(MKDIR) .tmp/seqtube1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/seqtube1.0.0/ && $(COPY_FILE) --parents main.hh sha1sum.hh Database.hh .tmp/seqtube1.0.0/ && $(COPY_FILE) --parents main.cc ChatDialog.cc NetSocket.cc TextEdit.cc MongMsg.cc BlockRequest.cc SharedFile2.cc Block.cc SearchDialog.cc FileDownload.cc sha1sum.cc FileListItem.cc Database.cc .tmp/seqtube1.0.0/ && (cd `dirname .tmp/seqtube1.0.0` && $(TAR) seqtube1.0.0.tar seqtube1.0.0 && $(COMPRESS) seqtube1.0.0.tar) && $(MOVE) `dirname .tmp/seqtube1.0.0`/seqtube1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/seqtube1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_main.cpp moc_Database.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_main.cpp moc_Database.cpp
moc_main.cpp: Database.hh \
		main.hh
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) main.hh -o moc_main.cpp

moc_Database.cpp: Database.hh
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) Database.hh -o moc_Database.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

main.o: main.cc main.hh \
		Database.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cc

ChatDialog.o: ChatDialog.cc main.hh \
		Database.hh \
		sha1sum.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ChatDialog.o ChatDialog.cc

NetSocket.o: NetSocket.cc main.hh \
		Database.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o NetSocket.o NetSocket.cc

TextEdit.o: TextEdit.cc main.hh \
		Database.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TextEdit.o TextEdit.cc

MongMsg.o: MongMsg.cc main.hh \
		Database.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MongMsg.o MongMsg.cc

BlockRequest.o: BlockRequest.cc main.hh \
		Database.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BlockRequest.o BlockRequest.cc

SharedFile2.o: SharedFile2.cc main.hh \
		Database.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SharedFile2.o SharedFile2.cc

Block.o: Block.cc main.hh \
		Database.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Block.o Block.cc

SearchDialog.o: SearchDialog.cc main.hh \
		Database.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SearchDialog.o SearchDialog.cc

FileDownload.o: FileDownload.cc main.hh \
		Database.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o FileDownload.o FileDownload.cc

sha1sum.o: sha1sum.cc 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sha1sum.o sha1sum.cc

FileListItem.o: FileListItem.cc main.hh \
		Database.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o FileListItem.o FileListItem.cc

Database.o: Database.cc Database.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Database.o Database.cc

moc_main.o: moc_main.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_main.o moc_main.cpp

moc_Database.o: moc_Database.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Database.o moc_Database.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

